[program:brave]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=bash -c "rm -rf /home/neko/.config/brave && mkdir -p /home/neko/.config/brave/Default && python3 -c \"import json;json.dump({'browser':{'has_seen_welcome_page':True},'brave':{'welcome_page_shown':True},'profile':{'exit_type':'Normal','exited_cleanly':True}},open('/home/neko/.config/brave/Default/Preferences','w'))\" && /usr/bin/brave-browser --no-sandbox --disable-gpu --enable-remote-extensions --disable-extensions-except=/usr/share/chromium/extensions/envoy --load-extension=/usr/share/chromium/extensions/envoy --disable-extensions-file-access-check --disable-extensions-http-throttling --window-position=0,0 --display=%(ENV_DISPLAY)s --user-data-dir=/home/neko/.config/brave --no-first-run --disable-brave-update --disable-brave-rewards-extension --start-maximized --no-default-browser-check --disable-dev-shm-usage --disable-breakpad --disable-crash-reporter --disable-session-crashed-bubble --hide-crash-restore-bubble --disable-infobars about:blank"
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/brave.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
redirect_stderr=true

[program:openbox]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/openbox --config-file /etc/neko/openbox.xml
autorestart=true
priority=300
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/openbox.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
redirect_stderr=true
