[program:x11vnc]
command=x11vnc -display :99.0 -nopw -listen 0.0.0.0 -rfbport 5900 -shared -forever -noxdamage
autorestart=true
priority=400
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/x11vnc.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true
